const skillsList = [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "Web development",
    "HTML",
    "CSS",
    "Mobile development",
    "iOS",
    "Android",
    "Flutter",
    "SQL",
    "NoSQL",
    "Node.js",
    "Express",
    "Spring Boot",
    "Spring",
    "Django",
    "Flask",
    "FastAPI",
    "AWS",
    "Azure",
    "GCP",
    "ReactJS",
    "Angular",
    "Front end",
    "Back end",
    "Full stack",
    "Research",
    "Multimedia content creation",
    "Ed platform",
    "Student",
  ]